# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('chat_type', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['chat_id'],
                'db_table': 'chats',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('from_first_name', models.CharField(max_length=200, verbose_name='senders first name')),
                ('from_last_name', models.CharField(max_length=50, verbose_name='senders user name')),
                ('message_type', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=500)),
                ('update_id', models.IntegerField()),
                ('is_bot', models.BooleanField()),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botapi.Chat')),
            ],
            options={
                'ordering': ['message_id'],
                'db_table': 'messages',
                'get_latest_by': ['-priority', 'date'],
            },
        ),
    ]
